# fly.toml app configuration file generated for weathered-field-6022 on 2023-10-08T15:28:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-field-6022"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
